// ESM entry. Imports the single data module (a CommonJS module generated by the
// pipeline). Node ESM imports CJS natively, exposing module.exports as the
// default import, so there is exactly one copy of the data on disk and no Node
// built-ins are used. esbuild inlines it when bundling for the browser.
import DATA from '../data/core-data.cjs';
import { createCore } from './core.mjs';

const core = createCore(DATA);

export const validate = core.validate;
export const isWellFormed = core.isWellFormed;
export const getDetails = core.getDetails;
export const getState = core.getState;
export const getDistricts = core.getDistricts;
export const listStates = core.listStates;
export const listDistricts = core.listDistricts;
export const getPincodes = core.getPincodes;
export const preload = core.preload;
export const DATA_VERSION = core.DATA_VERSION;
export const searchDistricts = core.searchDistricts; // deprecated v1 alias
export const lookup = core.lookup;
export const findNearby = core.findNearby;
export const reverseLookup = core.reverseLookup;
export const getCentroid = core.getCentroid;

// Internal, used by the geo package to share the decoded pincode index.
export const _decode = core._decode;

export default core;
