// ESM entry. Imports the embedded data module (generated by the pipeline) and
// wires it into the shared core logic. No Node built-ins.
import DATA from '../data/core-data.mjs';
import { createCore } from './core.mjs';

const core = createCore(DATA);

export const validate = core.validate;
export const isWellFormed = core.isWellFormed;
export const getDetails = core.getDetails;
export const getState = core.getState;
export const getDistricts = core.getDistricts;
export const listStates = core.listStates;
export const listDistricts = core.listDistricts;
export const getPincodes = core.getPincodes;
export const preload = core.preload;
export const DATA_VERSION = core.DATA_VERSION;
export const searchDistricts = core.searchDistricts; // deprecated v1 alias
export const lookup = core.lookup;
export const findNearby = core.findNearby;
export const reverseLookup = core.reverseLookup;
export const getCentroid = core.getCentroid;

// Internal, used by the geo package to share the decoded pincode index.
export const _decode = core._decode;

export default core;
